spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paypocket
    username: postgres
    password: postgres

  jpa:
    show-sql: true

logging:
  level:
    com.paypocket: DEBUG
    org.hibernate.SQL: DEBUG